/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface WrDrawingPad {
      'first': string;
      'last': string;
    }
  }

  interface HTMLWrDrawingPadElement extends StencilComponents.WrDrawingPad, HTMLStencilElement {}

  var HTMLWrDrawingPadElement: {
    prototype: HTMLWrDrawingPadElement;
    new (): HTMLWrDrawingPadElement;
  };
  interface HTMLElementTagNameMap {
    'wr-drawing-pad': HTMLWrDrawingPadElement;
  }
  interface ElementTagNameMap {
    'wr-drawing-pad': HTMLWrDrawingPadElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'wr-drawing-pad': JSXElements.WrDrawingPadAttributes;
    }
  }
  namespace JSXElements {
    export interface WrDrawingPadAttributes extends HTMLAttributes {
      'first'?: string;
      'last'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;